name: Style, Security, Tests

on: push

jobs:
  style_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Style checking
        run: |
          make lint

  security_checks:
    needs: style_checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Security checking
        run: |
          make security_checks

  unit_tests:
    needs: style_checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build -t tests -f docker/tests/Dockerfile .
      - name: Run tests
        run: |
          docker run --rm tests make unit_tests

  functional_tests:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Create env file
        run: |
          touch .env
          echo POSTGRES_DB="test_db" >> .env
          echo POSTGRES_USER="test_user" >> .env
          echo POSTGRES_PASSWORD="test_password" >> .env
          echo HOST="db" >> .env
          cat .env
      - name: Build docker-compose
        run: |
          docker-compose build tests
      - name: Run tests
        run: |
          docker-compose run tests make func_tests